#! /bin/bash
#
# basic checks to start install
NEXT=0

if [ "$1" == "--compile" ]; then
   cd GUI
   make
   if [ $? -eq 0 ] ; then
      cd ..
   else
      exit 1
   fi
fi

if [ $HOME = "/home/$USER" ]; then
   echo "ok"
   echo $HOME
   echo "$HOME" > scripts/.home_path
else
   IFS=/
   for i in $PWD; do
      if [ "$i" = "home" ]; then
         NEXT=1
      elif [ "$NEXT" = "1" ]; then
         IFS=$'\t\n'
         HOME="/home/${i}"
         echo $HOME
         echo "$HOME" > scripts/.home_path
         NEXT=0
      fi
   done
fi
HOME=$(head scripts/.home_path)
LOCAL_SETUP=${HOME}/QuickSetup
INTERNET_CHECK=${HOME}/QuickSetup/.internet_check.log

# check internet connection
ck_internet()
{
ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` > /dev/null && echo "ok" > $INTERNET_CHECK || echo "no" > $INTERNET_CHECK
echo "Internet: "$(head $INTERNET_CHECK)
}

# check if it's placed in the correct location
if [ "$PWD" == "${HOME}/QuickSetup" ]; then
   echo "Location: ok"
   ck_internet
   gksu -S -D QuickSetup ${HOME}/QuickSetup/GUI/QuickSetup
else
   echo "Location: not ok"
   mkdir -p $LOCAL_SETUP
   ck_internet
   cp -R ./* ${HOME}/QuickSetup && gksu ${HOME}/QuickSetup/GUI/QuickSetup
fi

