#!/bin/bash
#
# Enable vram as swap

vram_swap()
{
touch /etc/udev/rules.d/10-ps3vram-swap.rules && echo "20" && echo 'KERNEL=="ps3vram", ACTION=="add", RUN+="/sbin/mkswap /dev/ps3vram", RUN+="/sbin/swapon -p 10 /dev/ps3vram"' > /etc/udev/rules.d/10-ps3vram-swap.rules && echo "60" && echo "-Succesfully enabled vram-" && echo "Success"
}
echo "-Enabling vram-"
echo "20"
vram_swap
