#!/bin/bash
# kboot-ed
# Usage - kboot-ed resolution_you_want 
# Available res 480i 480p 576i 576p 720p 1080i 1080p, for fullscreen use f480i for example
#
# kboot.conf location
KBOOT_FILE=/etc/kboot.conf

#get ps3videomode value for desired resolution - example: kboot-ed 720p
value="$1"

#Fullscreen
if [ "$value" = "f480i" ]; then
	VIDEO_RES="129"
	value="480i Fullscreen"
elif [ "$value" = "f576p" ]; then
	VIDEO_RES="135"
	value="576p Fullscreen"
elif [ "$value" = "f720p" ]; then
	VIDEO_RES="131"
	value="720p Fullscreen"
elif [ "$value" = "f1080i" ]; then
	VIDEO_RES="132"
	value="1080i Fullscreen"
elif [ "$value" = "f1080p" ]; then
	VIDEO_RES="133"
	value="1080p Fullscreen"
#Regular
elif [ "$value" = "480i" ]; then
	VIDEO_RES="1"
elif [ "$value" = "576p" ]; then
	VIDEO_RES="7"
elif [ "$value" = "720p" ]; then
	VIDEO_RES="3"
elif [ "$value" = "1080i" ]; then
	VIDEO_RES="4"
elif [ "$value" = "1080p" ]; then
	VIDEO_RES="5"
else
	echo "-Unsupported video mode-"
	VIDEO_RES="131"
fi

kboot_edit()
{
	IFS=$'\t\n'
	echo "20"
	echo "-Reading current kboot.conf-"
	#searches label id and timeout
	while read LINE
		do
		if [ "$(echo "$LINE" | awk '{ print index($0,"default=") }')" != "0" ]; then
				KBOOT_DEFAULT_LABEL=$LINE
				KBOOT_L=$(echo "$LINE" | sed "s/default=//g")
		fi
		if [ "$(echo "$LINE" | awk '{ print index($0,"timeout=") }')" != "0" ]; then
				KBOOT_TIMEOUT=$LINE
		fi	
	done <$KBOOT_FILE

	IFS=$' \t\n'
	#searches root id and video mode (if used)
	echo "30"
	echo "-Looking for root id and previous modes-"
	while read LINE
		do
		for n in $LINE; do
			if [ "$(echo "$n" | awk '{ print index($0,"root=UUID") }')" != "0" ]; then
				KBOOT_ROOT=$(echo "$n" | sed "s/'//g")
			fi
			if [ "$(echo "$n" | awk '{ print index($0,"video=ps3fb") }')" != "0" ]; then
				KBOOT_MODE=$(echo "$n" | sed "s/'//g")
			fi
		done 	
	done <$KBOOT_FILE

	#sets a default root
	if [ "$KBOOT_ROOT" = "" ]; then
		KBOOT_ROOT="root=/dev/ps3da1"
	fi
	if [ "$KBOOT_MODE" = "" ]; then
		KBOOT_MODE=""
	fi
	echo "30"
	echo "-Defining labels-"
	# define labels
	KBOOT_LABEL=$(echo $KBOOT_L"='/boot/vmlinux")
	KBOOT_LABEL_OLD=$(echo $KBOOT_L" old='/boot/vmlinux.old")
	
	#backup kboot.conf file
	echo "10"
	echo "-Creating backup in /tmp/kboot.conf.old-"
	mv $KBOOT_FILE /tmp/kboot.conf.old 
	#creates a kboot.conf and then copies selected options
	echo "message=/etc/kboot.msg" >> $KBOOT_FILE
	echo "$KBOOT_DEFAULT_LABEL" >> $KBOOT_FILE
	echo "$KBOOT_TIMEOUT" >> $KBOOT_FILE
	echo "$KBOOT_LABEL initrd=/boot/initrd.img $KBOOT_ROOT quiet video=ps3fb:mode:$VIDEO_RES'" >> $KBOOT_FILE
	echo "$KBOOT_LABEL_OLD initrd=/boot/initrd.img.old $KBOOT_ROOT quiet $KBOOT_MODE'" >> $KBOOT_FILE
	
	echo "10"
	echo "-Changed resolution to $value-"
	echo "Success"
}

kboot_edit
