#!/bin/bash
# osxmb installer

HOME=$(head scripts/.home_path)
echo "10"
echo "-Installing osxmb-"
cp $HOME/QuickSetup/scripts/Other/osxmb/joy.png /usr/share/icons
cp $HOME/QuickSetup/scripts/Other/osxmb/reboot.png /usr/share/icons
cp $HOME/QuickSetup/scripts/Other/osxmb/shutdown.png /usr/share/icons
cp $HOME/QuickSetup/scripts/Other/osxmb/xmb.png /usr/share/icons 
cp $HOME/QuickSetup/scripts/Other/osxmb/osxmb /usr/local/bin && echo "#bin ok"
cp $HOME/QuickSetup/scripts/Other/osxmb/exit-ubuntu /usr/local/bin && echo "#exit-bin ok"
echo "30"
echo "-Installing GTKDialog"
apt-get install gtkdialog
echo "20" 
echo "-Creating launchers-"
cp $HOME/QuickSetup/scripts/Other/osxmb/osxmb.desktop /usr/share/applications
cp /usr/share/applications/osxmb.desktop ${HOME}/Desktop && echo "#shortcut ok"
chmod a+w ${HOME}/Desktop/osxmb.desktop && echo "#permissions ok"
echo "30"
echo "-osxmb finished installing-"
echo "100"
echo "Success"
