#!/bin/bash
# kboot-ed
# Usage - kboot-ed resolution_you_want 
# Available res 480i 480p 576i 576p 720p 1080i 1080p 


KBOOT_FILE=/etc/kboot.conf

JOBS="$1"
MODE="$2"

#kboot default values
KBOOT_MODE=""
KBOOT_="Ubuntu"
KBOOT_TIMEOUT=10
KBOOT_ROOT="root=/dev/sda1"
LKBOOT_DEFAULT_LABEL="default=Ubuntu"

if [ "$MODE" = "480i" ]; then
	MODE="129"
elif [ "$value" = "480p" ]; then
	MODE="130"
elif [ "$value" = "576i" ]; then
	MODE="134"
elif [ "$value" = "576p" ]; then
	MODE="135"
elif [ "$MODE" = "720p" ]; then
	MODE="131"
elif [ "$MODE" = "1080i" ]; then
	MODE="132"
elif [ "$MODE" = "1080p" ]; then
	MODE="133"
else
	echo "-Unsupported resolution, defaults to 720p"
	MODE="131"
fi

fbset_calc()
{
	sudo apt-get install fbset
	sudo fbset
}

kboot_edit()
{

IFS=$'\t\n'
#searches label id and timeout
while read LINE
		do
		if [ "$(echo "$LINE" | awk '{ print index($0,"default=") }')" != "0" ]; then
				KBOOT_DEFAULT_LABEL=$LINE
				KBOOT_L=$(echo "$LINE" | sed "s/default=//g")
		fi
		if [ "$(echo "$LINE" | awk '{ print index($0,"timeout=") }')" != "0" ]; then
				KBOOT_TIMEOUT=$LINE
		fi	
done <$KBOOT_FILE

IFS=$' \t\n'
#searches root id and video mode (if used)
while read LINE
		do
		for n in $LINE; do
			if [ "$(echo "$n" | awk '{ print index($0,"root=UUID") }')" != "0" ]; then
				KBOOT_ROOT=$(echo "$n" | sed "s/'//g")
			fi
			if [ "$(echo "$n" | awk '{ print index($0,"video=ps3fb") }')" != "0" ]; then
				KBOOT_MODE=$(echo "$n" | sed "s/'//g")
			fi
		done 	
done <$KBOOT_FILE

# define labels
KBOOT_LABEL=$(echo $KBOOT_L"='/boot/vmlinux")
KBOOT_LABEL_OLD=$(echo $KBOOT_L" old='/boot/vmlinux.old")

#backup kboot.conf file
mv $KBOOT_FILE /tmp/kboot.conf.old 
#creates a kboot.conf and then copies selected options
echo "message=/etc/kboot.msg" >> $KBOOT_FILE
echo "$KBOOT_DEFAULT_LABEL" >> $KBOOT_FILE
echo "$KBOOT_TIMEOUT" >> $KBOOT_FILE
echo "$KBOOT_LABEL initrd=/boot/initrd.img $KBOOT_ROOT quiet video=ps3fb:mode:$MODE'" >> $KBOOT_FILE
echo "$KBOOT_LABEL_OLD initrd=/boot/initrd.img.old $KBOOT_ROOT quiet $KBOOT_MODE'" >> $KBOOT_FILE
}
if [ "$JOBS" = "both" ]; then
	kboot_edit
	fbset_calc
	fbset_edit
elif [ "$JOBS" = "fbset" ]; then
	fbset_edit
elif [ "$JOBS" = "video" ]; then
	kboot_edit
fi
