#!/bin/bash
#
# other-install
# Usage: other-install ( packages full-install non-available medibuntu ) one option at a time
# by defpy

HOME=$(head .home_path)

# Files to be installed
# ATTENTION - Names and URLs must be separated by spaces

PACKAGES="emesene mplayer lame xaralx "
MEDIBUNTU="libdvdcss2 mencoder"

FILES="http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-3.3/gcc-3.3-base_3.3.6-10_powerpc.deb http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-3.3/libstdc++5_3.3.6-10_powerpc.deb http://packages.medibuntu.org/pool/non-free/p/ppc-codecs/ppc-codecs_20071007-0medibuntu1_powerpc.deb"
FILE_NAMES="gcc-3.3-base_3.3.6-10_powerpc.deb libstdc++5_3.3.6-10_powerpc.deb ppc-codecs_20071007-0medibuntu1_powerpc.deb"

# Download path
DOWNLOAD=${HOME}/QuickSetup/scripts/downloads

# Add medibuntu repo function
add_medibuntu_repo()
{
	wget http://www.medibuntu.org/sources.list.d/`lsb_release -cs`.list --output-document=/etc/apt/sources.list.d/medibuntu.list && apt-get -q update && apt-get --yes -q --allow-unauthenticated install medibuntu-keyring && apt-get -q update
	apt-get install -y $MEDIBUNTU && echo "Ok" || echo "Failed"
	echo "#Setting medibuntu @10" >> $LOG
}

# Install ubuntu packages
install_packages()
{
	apt-get install -y $PACKAGES && echo "Ok" || echo "Failed"
	echo "#Installing packages @20" >> $LOG
}

# Download and install non-available in repos
get_non_available()
{
	mkdir -p $DOWNLOAD
	cd $DOWNLOAD
	for i in $FILES; do
		wget $i && echo "File $i downloaded" || echo "Failed to download $i"
	done
	for i in $FILE_NAMES; do
		dpkg -i $i && echo "File $i installed" || echo "Failed to install $i"
	done
	echo "#Installing ppc-codecs @10" >> $LOG
}

# Define option
if [ "$1" == "full-install" ]; then
	install_packages
	get_non_available
	add_medibuntu_repo
elif [ "$1" == "non-available" ]; then
	get_non_available
elif [ "$1" == "packages" ]; then
	install_packages
elif [ "$1" == "medibuntu" ]; then
	add_medibuntu_repo
else
	echo "Usage: other-install ( packages full-install non-available medibuntu ) "
fi
