#!/bin/bash
#
# Disable ubuntu services located in /etc/init.d

# List of services to be disabled (must be separated by spaces)
SERVICES="alsa anacron apmd atd cupsys dns-clean evms fetchmail gdomap hotkey-setup hotplug hotplug-net hplib ifrename inetd inetd.real ivm mdamd mdamd-raid portmap ppp ppp-dns rmnologin rsync"
# Change percentage according to the number of services
PERCENT=4

disable_services()
{
	for n in $SERVICES; do 
		update-rc.d -f $n remove && echo "-Disabling $n-" || echo "-Failed to disable $n-"
		echo $PERCENT
	done
	echo "-Done disabling services-"
	echo "100"
	echo "Success"
}
disable_services

