#!/bin/bash
#
# Disable ubuntu services located in /etc/init.d

# List of services to be disabled (must be separated by spaces)
SERVICES="bluetooth cups cron anacron laptop-mode"
# Change percentage according to the number of services
PERCENT=20

disable_services()
{
	for n in $SERVICES; do 
		update-rc.d -f $n remove && echo "-Disabling $n-" || echo "-Failed to disable $n-"
		echo $PERCENT
	done
	echo "-Done disabling services-"
	echo "Success"
}
disable_services

