#!/bin/bash

FBSET_FILE=/etc/init.d/fbset.sh
FBSET_OLD=/etc/init.d/fbset.sh.old

FbsetX="$1"
FbsetY="$2"

IsInteger() 
{
    [ "$1" -eq "$1" ] > /dev/null 2>&1
    return $?
}

DoTheMath()
{
	if [ "$element" = "129" ]; then
		TempX=640-$ReturnX
		TempX=$TempX/2
		ReturnX=$TempX+$ReturnX
		TempY=480-$ReturnY
		TempY=$TempY/2
		ReturnY=$TempY+$ReturnY	
	fi
	if [ "$element" = "135" ]; then
		TempX=704-$ReturnX
		TempX=$TempX/2
		ReturnX=$TempX+$ReturnX
		TempY=576-$ReturnY
		TempY=$TempY/2
		ReturnY=$TempY+$ReturnY	
	fi
	if [ "$element" = "131" ]; then
		TempX=1280-$ReturnX
		TempX=$TempX/2
		ReturnX=$TempX+$ReturnX
		TempY=720-$ReturnY
		TempY=$TempY/2
		ReturnY=$TempY+$ReturnY	
	fi
	if [ "$element" = "132" ]; then
		TempX=1920-$ReturnX
		TempX=$TempX/2
		ReturnX=$TempX+$ReturnX
		TempY=1080-$ReturnY
		TempY=$TempY/2
		ReturnY=$TempY+$ReturnY	
	fi
	if [ "$element" = "133" ]; then
		TempX=1920-$ReturnX
		TempX=$TempX/2
		ReturnX=$TempX+$ReturnX
		TempY=1920-$ReturnY
		TempY=$TempY/2
		ReturnY=$TempY+$ReturnY
	fi
}

ReturnValue()
{
	echo $ReturnX
	echo $ReturnY
}

ReadFbset ()
{
	FBSET=$(fbset)

	# Get X value
	for element in $string; do
    	if $(is_integer $element) ; then
      		if [ $element -gt 400 ];then
         		ReturnX=$element
         		echo $ReturnX
			fi
    	fi
	done
	# Get Y value
	for element in $string; do
    	if $(is_integer $element) ; then
      		if [ $element -gt 300 ];then
         		if [ ! $ReturnX -eq $element ]; then
					ReturnY=$element
         			echo $ReturnY
				fi
			fi
    	fi
	done

	# Get the video mode
	string=$(grep "/boot/vmlinux " /etc/kboot.conf | sed "s/:/ /g")
	for element in $string; do
		if $(is_integer $element) ; then
			if [ $element -gt 100 ];then
				Mode=$element
				DoTheMath
				ReturnValue
	      	else
	            ReturnValue
			fi
	    fi
	done
}

WriteFbset ()
{
	if [ -f $FBSET_FILE ]; then
		mv $FBSET_FILE $FBSET_OLD
	else
		echo "20"
		echo "-Installing fbset-"
		apt-get install fbset
	fi

	echo "30"
	echo "-Writing fbset values-"
	echo "#!/bin/sh -e" >> $FBSET_FILE
	echo "fbset -a -xres $FbsetX -yres $FbsetY -vxres $FbsetX -vyres $FbsetY" >> $FBSET_FILE
	echo "exit 0" >> $FBSET_FILE

	echo "30"
	echo "-Making fbset.sh executable-"
	chmod 755 /etc/init.d/fbset.sh

	echo "20"
	echo "-Creating symbolic links-"
	sudo ln -s /etc/init.d/fbset.sh /etc/rc1.d/S26fbset
	sudo ln -s /etc/init.d/fbset.sh /etc/rc2.d/S26fbset

	echo "40"
	echo "-Done, your new resolution is $FbsetX X $FbsetY-"
	echo "Success"
}

if [ $1 = "read" ]; then
	ReadFbset
elif [ $1 = "test" ]; then
	TestFbset
else
	WriteFbset
fi

