#!/bin/bash

FBSET_FILE=/etc/init.d/fbset.sh
FBSET_OLD=/etc/init.d/fbset.sh.old
KBOOT_FILE=/etc/kboot.conf

FbsetX="$1"
FbsetY="$2"

GetNum()
{
	echo $2
}

ReadFbset ()
{
	FBSET=$(fbset)
	GetNum $FBSET
}

WriteFbset ()
{
	if [ -f $FBSET_FILE ]; then
		mv $FBSET_FILE $FBSET_OLD
	else
		echo "20"
		echo "-Installing fbset-"
		apt-get install fbset
	fi

	echo "30"
	echo "-Writing fbset values-"
	echo "#!/bin/sh -e" >> $FBSET_FILE
	echo "fbset -a -xres $FbsetX -yres $FbsetY -vxres $FbsetX -vyres $FbsetY" >> $FBSET_FILE
	echo "exit 0" >> $FBSET_FILE

	echo "30"
	echo "-Making fbset.sh executable-"
	chmod 755 /etc/init.d/fbset.sh

	echo "20"
	echo "-Creating symbolic links-"
	sudo ln -s /etc/init.d/fbset.sh /etc/rc1.d/S26fbset
	sudo ln -s /etc/init.d/fbset.sh /etc/rc2.d/S26fbset

	echo "40"
	echo "-Done, your new resolution is $FbsetX X $FbsetY-"
	echo "Success"
}

if [ $1 = "read" ]; then
	ReadFbset
elif [ $1 = "test" ]; then
	TestFbset
else
	WriteFbset
fi

