#!/bin/bash

# This script will install spu-medialib, install mplayer and make it's setup.
# Spu-medialib is a multimedia framework, created by Unsolo, that uses SPUs of Cell BE for colour conversation.
# Mplayer-ps3 is mplayer binary patched for spu-medialib.
# The whole meaning of this script is to give users of linux on Playstation 3 platform smooth video playback of both SD and HD content.

PROFILE=${HOME}/QuickSetup/other/%gconf.xml
MPLAYERPROFILE=${HOME}/QuickSetup/other/mplayer/%gconf.xml

# A special gnome-terminal profile configuration

PMPLAYER=${HOME}/QuickSetup/other/PS3MoviePlayer

LOG=${HOME}/QuickSetup/scripts/.install_log
DOWNLOAD=${HOME}/QuickSetup/scripts/downloads


# Download spu-medialib

wget http://linux.yes.nu/PS3Ubuntu/files/spu-medialib_0.1git20071126-1_powerpc.deb && echo "Ok" || echo "Failed to download"

# Download mplayer-ps3 ( this binary is made by Stream btw )

wget http://proxima.isp.tula.ru:20080/mplayer-ps3/mplayer-ps3-29546-090904.zip && echo "Ok" || echo "Failed to download"


# Install spu-medialib

mv spu-medialib_0.1git20071126-1_powerpc.deb $DOWNLOAD
cd $DOWNLOAD
ar x spu-medialib_0.1git20071126-1_powerpc.deb
tar -xzf data.tar.gz
cd usr && cd local && cd bin
cp * /usr/local/bin
cd $DOWNLOAD && cd usr && cd lib
cp libspu-medialib.so.0.100.0 libspu-medialib.la libspu-medialib.a /usr/lib
ln -s /usr/lib/libspu-medialib.so.0.100.0 /usr/lib/libspu-medialib.so.0
ln -s /usr/lib/libspu-medialib.so.0 /usr/lib/libspu-medialib.so
cd pkgconfig
cp libspu-medialib.pc /usr/lib/pkgconfig
cd $DOWNLOAD && cd usr && cd include
cp -r spu-medialib /usr/include
echo "Ok"


# Install mplayer-ps3

cd ${HOME}
mv mplayer-ps3-29546-090904.zip $DOWNLOAD
apt-get install -y unzip && echo "Ok" || echo "Failed"
cd $DOWNLOAD
unzip mplayer-ps3-29546-090904.zip
cp mplayer-ps3 /usr/local/bin
echo "Ok"


# Setup

apt-get install -y gnome-terminal && echo "Ok" || echo "Failed"
# I didn't want to make it install gnome-terminal. But most psubuntu members use Xubuntu, which has Xfce terminal. And i have no idia about profiles of Xfce. Gconf is also part of GNOME, which is needed by this script.
cd ${HOME}/.gconf/apps/gnome-terminal
mkdir global
cp $PROFILE ${HOME}/.gconf/apps/gnome-terminal/global
cd ${HOME}/.gconf/apps/gnome-terminal/profiles
mkdir mplayer
cp $MPLAYERPROFILE ${HOME}/.gconf/apps/gnome-terminal/profiles/mplayer
cp $PMPLAYER /usr/bin
echo "Done"
echo "#Mplayer-ps3 setup @5" >> $LOG
