#!/bin/bash
# kboot-ed
# Usage - kboot-ed resolution_you_want 
# Available res 480i 480p 576i 576p 720p 1080i 1080p 
#
# kboot.conf location
# QuickSetup Log file

KBOOT_FILE=/etc/kboot.conf

#kboot default values
KBOOT_MODE=""
KBOOT_L="Ubuntu"
KBOOT_TIMEOUT="timeout=10"
KBOOT_ROOT="root=/dev/sda1"
KBOOT_DEFAULT_LABEL="default=Ubuntu"

#get ps3videomode value for desired resolution - example: kboot-ed 720p
value="$1"
if [ "$value" = "480i" ]; then
	VIDEO_RES="129"
elif [ "$value" = "480p" ]; then
	VIDEO_RES="130"
elif [ "$value" = "576i" ]; then
	VIDEO_RES="134"
elif [ "$value" = "576p" ]; then
	VIDEO_RES="135"
elif [ "$value" = "720p" ]; then
	VIDEO_RES="131"
elif [ "$value" = "1080i" ]; then
	VIDEO_RES="132"
elif [ "$value" = "1080p" ]; then
	VIDEO_RES="133"
else
	echo "-Unsupported video mode-"
	VIDEO_RES="131" 
fi

kboot_edit()
{
	IFS=$'\t\n'
	echo "20"
	echo "-Reading current kboot.conf-"
	#searches label id and timeout
	while read LINE
		do
		if [ "$(echo "$LINE" | awk '{ print index($0,"default=") }')" != "0" ]; then
				KBOOT_DEFAULT_LABEL=$LINE
				KBOOT_L=$(echo "$LINE" | sed "s/default=//g")
		fi
		if [ "$(echo "$LINE" | awk '{ print index($0,"timeout=") }')" != "0" ]; then
				KBOOT_TIMEOUT=$LINE
		fi	
	done <$KBOOT_FILE

	IFS=$' \t\n'
	#searches root id and video mode (if used)
	echo "30"
	echo "-Looking for root id and previous modes-"
	while read LINE
		do
		for n in $LINE; do
			if [ "$(echo "$n" | awk '{ print index($0,"root=UUID") }')" != "0" ]; then
				KBOOT_ROOT=$(echo "$n" | sed "s/'//g")
			fi
			if [ "$(echo "$n" | awk '{ print index($0,"video=ps3fb") }')" != "0" ]; then
				KBOOT_MODE=$(echo "$n" | sed "s/'//g")
			fi
		done 	
	done <$KBOOT_FILE

	echo "30"
	echo "-Defining labels-"
	# define labels
	KBOOT_LABEL=$(echo $KBOOT_L"='/boot/vmlinux")
	KBOOT_LABEL_OLD=$(echo $KBOOT_L" old='/boot/vmlinux.old")
	
	#backup kboot.conf file
	echo "10"
	echo "-Creating backup in /etc/kboot.conf.old-"
	mv $KBOOT_FILE /etc/kboot.conf.old 
	#creates a kboot.conf and then copies selected options
	echo "message=/etc/kboot.msg" >> $KBOOT_FILE
	echo "$KBOOT_DEFAULT_LABEL" >> $KBOOT_FILE
	echo "$KBOOT_TIMEOUT" >> $KBOOT_FILE
	echo "$KBOOT_LABEL initrd=/boot/initrd.img $KBOOT_ROOT quiet video=ps3fb:mode:$VIDEO_RES'" >> $KBOOT_FILE
	echo "$KBOOT_LABEL_OLD initrd=/boot/initrd.img.old $KBOOT_ROOT quiet $KBOOT_MODE'" >> $KBOOT_FILE
	
	echo "10"
	echo "-Changed resolution to $value-"
	echo "Success"
}

kboot_edit
