#!/bin/bash
#
# youtube-option
# Installs firefox-greasemonkey, adds Youtube without Flash Auto (Copyright (c) 2009, Arne Schneck) 
# adds youtube_without_flash to greasemonkey config.xml 
# by defpy

# QuickSetup Log file
HOME=$(head .home_path)

XML_HEAD="<UserScriptConfig>"
STATE=0
TAG_A=0
TAG_B=0
TAG_NAME=""
XML_STATE="ok"

get_path()
{
	F_PATH=$(grep -i "Path" ${HOME}/.mozilla/firefox-3.5/profiles.ini | sed 's/[pP][aA][tT][hH]=//g')
	LOC=${HOME}/.mozilla/firefox-3.5/
	if [ "$F_PATH" = "" ]; then
		F_PATH=$(grep -i "Path" ${HOME}/.mozilla/firefox/profiles.ini | sed 's/[pP][aA][tT][hH]=//g')
		LOC=${HOME}/.mozilla/firefox/
	fi
	export FIREFOX_PATH=$LOC$F_PATH
	XML_FILE=${FIREFOX_PATH}/gm_scripts/config.xml
	XML_FILE_BK=${FIREFOX_PATH}/gm_scripts/config.xml_bk
	GREASE_PATH=${FIREFOX_PATH}/gm_scripts
	echo $FIREFOX_PATH
}
get_path
# adds metainfo to greasemonkey config.xml
include_tags()
{
	mv $XML_FILE $XML_FILE_BK
	echo -e "\n" >> $XML_FILE_BK
	while read LINE; do 
		if [ "$(echo "$LINE" | awk '{ print index($0,"</UserScriptConfig>") }')" = "0" ]; then
			echo "$LINE" >> $XML_FILE
		else
			#skip line
			XML_STATE="check"
		fi
	done < $XML_FILE_BK
	if [ "$XML_STATE" == "check" ]; then
		echo '<Script filename="youtube_without_flashx.user.js" name="Youtube without Flash Auto" namespace="none" description="Adds links below the Youtube video to (a) download the video (HD .mp4 file, no converters are used, no external sites) (b) view the video with an embedded external player (like mplayerplug-in or the totem plugin) " enabled="true" basedir="youtube_without_flashx">' >> $XML_FILE
		echo '<Include>http://youtube.*/watch*</Include>' >> $XML_FILE
		echo '<Include>http://*.youtube.*/watch*</Include>' >> $XML_FILE
		echo '</Script>' >> $XML_FILE
		echo '</UserScriptConfig>' >> $XML_FILE
		echo "Changes made to config.xml"
		mkdir -p ${GREASE_PATH}/youtube_without_flashx
		cp -R ${HOME}/QuickSetup/scripts/youtube_without_flashx.user.js ${GREASE_PATH}/youtube_without_flashx
		chmod a+w -R ${GREASE_PATH}/config.xml
		chmod a+w -R ${GREASE_PATH}/youtube_without_flashx
	else
		echo "No modifications made to config.xml"
	fi
}

# dirty parsing, should be replaced by a proper xml parser
process()
{
TAGS="<UserScriptConfig </UserScriptConfig <Script </Script <Include </Include"
for i in $TAGS; do
	if [ $STATE = 0 ]; then 
		TAG_A=$(grep "$i" $XML_FILE | wc -l)
		STATE=1
		TAG_NAME="$i"
	elif [ $STATE = 1 ]; then
		TAG_B=$(grep "$i" $XML_FILE | wc -l)
		STATE=2
	fi
	if [ $STATE = 2 ]; then
		if [ $TAG_A = $TAG_B ]; then
			echo $TAG_A" "$TAG_B" "$TAG_NAME "- OK"
		else
			echo $TAG_A" "$TAG_B" "$TAG_NAME "- NO (tags uneven)"
			XML_STATE="no"
		fi
		STATE=0
	fi
done
}

# Checks for greasemonkey config traces, if found add youtube-script to existing install. Clean install is done if nothing is found
start()
{
echo $XML_FILE
if [ -e "$XML_FILE" ]; then
	echo "config.xml - found"
	process
	if [ "$XML_STATE" = "ok" ]; then
		include_tags
	else
		echo "XML not ok"
	fi
else
	echo "config.xml - not found (clean install)"
	if [ -e "$GREASE_PATH" ]; then
		echo "Greasemonkey directory found"
		cp -R ${HOME}/QuickSetup/scripts/config.xml $GREASE_PATH
		cp -R ${HOME}/QuickSetup/scripts/youtube_without_flashx.user.js ${GREASE_PATH}/youtube_without_flashx
		chmod a+w -R ${GREASE_PATH}/config.xml
		chmod a+w -R ${GREASE_PATH}/youtube_without_flashx
	else
		echo "Greasemonkey directory not found, creating..."
		mkdir -p ${GREASE_PATH}/youtube_without_flashx
		cp -R ${HOME}/QuickSetup/scripts/config.xml $GREASE_PATH
		cp -R ${HOME}/QuickSetup/scripts/youtube_without_flashx.user.js ${GREASE_PATH}/youtube_without_flashx
		chmod a+w -R ${GREASE_PATH}/config.xml
		chmod a+w -R ${GREASE_PATH}/youtube_without_flashx
	fi
fi

}

# Install firefox-greasemonkey and start config process
apt-get install -y firefox-greasemonkey && start || echo "Failed to start youtube-option"

