#!/bin/bash

HOME=$(head scripts/.home_path)

if [ -f scripts/.QuickRun ]; then
	echo "Success"
else
	echo "#This is the first time you ran QuickSetup on this system."
	echo "#Either that, or you removed scripts/.QuickSetup."
	echo "-Setting up QuickSetup-"
	echo "20"
	echo "-Creating QuickSetup launcher-"
	cp $HOME/QuickSetup/GUI/Graphics/PSUIcon.png /usr/share/icons/PSUbuntu.png
	echo "20"
	cp $HOME/QuickSetup/scripts/.QuickSetup.desktop /usr/share/applications/QuickSetup.desktop
	echo "20"
	cp $HOME/QuickSetup/scripts/.QuickSetup /usr/local/bin/QuickSetup
	echo "40"
	echo "-QuickSetup was succesfully installed-"
	echo "#From now on you can launch QuickSetup from the system menu"
	echo "#You can also use the terminal command \"QuickSetup\""
	echo "#For more information: QuickSetup --help"
	echo "THIS FILE INDICATES QUICKSETUP RAN BEFORE" > $HOME/QuickSetup/scripts/.QuickRun
	echo "Success"
fi
	
